### PR TITLE
Implement input for db user

### PR DESCRIPTION
**Pull request by juliusvdijk**
This is needed for server support as it is unwise to connect to the database as root.

### CODE REVIEW

**Comment by StenSipma** [comment]
Ah I see what you want. I will add this to the dev-web branch if you don't mind.

I'll reference the PR.

**Comment by StenSipma** [comment]
Here is the PR: #75 
You can close this one if you think that is enough. There are some additional changes I made earlier with the ip.

**Comment by juliusvdijk** [comment]
@StenSipma Kan je de documentatie van hoe de server te starten via de CLI dan gaat aangezien de server geen vagrant draait.

**Comment by StenSipma** [comment]
Als je in de `$PROJECT_ROOT/API/` folder zit, kan je `make` runnen die doet eerst wat checks en dan compiled ie. (als je de checks niet wil kan je  ook `make build` doen).

`make run` werkt ook, dan compiled en runt ie de api. Vervolgens moet je wel de username etc geven.

**Pull request closed without merging**
